Change readinessprobe

diff --git a/.tekton/docker-build-cluster.yaml b/.tekton/docker-build-cluster.yaml
--- a/.tekton/docker-build-cluster.yaml
+++ b/.tekton/docker-build-cluster.yaml
@@ -124,25 +124,33 @@ spec:
             sleep 3
           done
 
-          echo "build cluster seems up & running and port-forward is ok"
+          echo "build cluster seems up & running and port-forward is ok" | tee /cluster/build/docker/up
           # Now time to keep this sidecar container up & running ?
           # sleep infinity
-          trap : TERM INT; sleep infinity & wait
+          # trap : TERM INT; sleep infinity & wait
+          ls -l /cluster/build/docker
 
       volumeMounts:
         - mountPath: /cd-config
           name: cd-config-volume
+        - mountPath: /cluster/build/docker
+          name: sidecar-volume          
       # Wait for the port foward to be available
       readinessProbe:
-        tcpSocket:
-          port: 2375
-        initialDelaySeconds: 10
-        periodSeconds: 10
-        failureThreshold: 12
+        # tcpSocket:
+        #   port: 2375
+        # initialDelaySeconds: 10
+        # periodSeconds: 10
+        # failureThreshold: 12
+        periodSeconds: 1
+        exec:
+          command: ["ls", "/cluster/build/docker/up"]
   volumes:
     - name: task-volume
       persistentVolumeClaim:
         claimName: $(inputs.params.task-pvc)
+    - name: sidecar-volume
+      emptyDir: {}
     - name: cd-config-volume
       configMap:
         name: toolchain
